{{- if or .Values.config.cassandraUser .Values.config.cassandraPassword }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "examon-server.fullname" . }}
  labels:
    {{- include "examon-server.labels" . | nindent 4 }}
type: Opaque
stringData:
  cassandra-user: {{ .Values.config.cassandraUser | quote }}
  cassandra-password: {{ .Values.config.cassandraPassword | quote }}
{{- end }}
